removed the empty space on the right of the header and shifted buttons
GDSCITM/GDSCITM-official-website pull request #139
Opened 2023-04-05 17:47 UTC by vladutvoicu

**Notes for Reviewers**

This PR fixes #129 

Describe the changes you've made:

removed the empty space on the right of the header and shifted buttons (changes made to "src/Components/Alternative/Header.module.css")

Screenshots for the change:

![2c5251724a69638f35dd0b685b757ab9](https://user-images.githubusercontent.com/107242590/230161622-6498065e-80cc-4d9c-bd8d-dac420fa274d.png)

2023-04-06 05:51 UTC, ArunPatel02 requested changes
@vladutvoicu  could you please  decreases the space between two navigation menu and instead of justify-center : space-evenly can you implement justify-end and give margin from right.

![image](https://user-images.githubusercontent.com/89798093/230282991-608ab664-b052-45e2-8002-30083af6eab2.png)

2023-04-06 09:36 UTC, Yashsharma1911 commented
some good reviews here @vladutvoicu from @ArunPatel02 do you need any help?

2023-04-06 09:39 UTC, vladutvoicu commented
> some good reviews here @vladutvoicu from @ArunPatel02 do you need any help?

Working on it right now

2023-04-06 10:18 UTC, vladutvoicu commented
I changed justify-content to "flex-end" and added margin to the right side

![e86a71e0d8300ea154294b283eabd55a (1)](https://user-images.githubusercontent.com/107242590/230348262-2d01ee3c-d65c-4a83-a326-273db86ba1c3.png)

2023-04-07 05:23 UTC, ArunPatel02 approved these changes

2023-04-07 05:24 UTC, ArunPatel02 commented
> I changed justify-content to "flex-end" and added margin to the right side
> 
> ![e86a71e0d8300ea154294b283eabd55a (1)](https://user-images.githubusercontent.com/107242590/230348262-2d01ee3c-d65c-4a83-a326-273db86ba1c3.png)

great work @vladutvoicu  thanks a lot for your contribution

2023-04-07 05:24 UTC, merged